---
title: "Cell type identification improvement"
output: html_notebook
---
### Setup knitr and load utility functions
```{r setup}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir="E:/DISC/reproducibility")
```
```{r}
utilities_path = "./source/utilities.r"
source(utilities_path)
```
### Filtering cells as Seurat tutorial
DISC outputs both values and compressed features after imputation.</br>
Here, we demostrate how to DISC compressed features for Seurat clustering using PBMC data.
```{r}
ds_dir = "./data/PBMC/ds_0.3"
observed_path = paste0(ds_dir, "/observed.loom")
observed_data = readh5_loom(observed_path)
expressed_cell = rowSums(observed_data > 0)
gene_expression = rowSums(observed_data)
gene_filter = expressed_cell >= 10 & gene_expression > expressed_cell * 1
used_genes = rownames(observed_data)[gene_filter]
DISC_values = readh5_imputation(paste0(ds_dir, "/DISC.hdf5"))[gene_filter, ]
DISC_features = readh5_feature(paste0(ds_dir, "/DISC_feature.hdf5"))
cell_type = readRDS("./results/PBMC/cell_type.rds")
cell_type_identification = seurat_classification(gene_bc_mat = DISC_values, feature_bc_mat = DISC_features, cell_type = cell_type, pca_dim = 10, res = 0.5, min_pct = 0.25, show = T, cell_type_identification_fun = cell_type_identification_pbmc)
```
```{r}
print(cell_type_identification[["summary"]]["ACC"])
print(cell_type_identification[["summary"]]["ARI"])
print(cell_type_identification[["cell_type_result"]][, "Jaccard"])
print(cell_type_identification[["cell_type_result"]][, "F1-score"])
print(cell_type_identification[["cell_type_result"]][, "ACC"])
```