---
title: "DEG Identification using 10X_5CL"
output: html_notebook
---
### Setup knitr and load utility functions
```{r setup}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir="E:/DISC/reproducibility")
```
```{r}
utilities_path = "./source/utilities.r"
source(utilities_path)
```
### Settings
```{r}
method_name = c("Raw", "DISC", "scVI", "MAGIC", "DCA", "scScope", "DeepImpute", "VIPER", "scImpute")
method_color = c("#A5A5A5", "#E83828", "#278BC4", "#EADE36", "#198B41", "#920783", "#F8B62D", "#8E5E32", "#1E2B68")
names(method_color) = method_name
text_color = rep("black", length(method_name))
names(text_color) = method_name
text_color["DISC"] = "red"
options(future.globals.maxSize= 1e9)
```
### Identify reference DEGs from bulk data.
```{r}
library(limma)
gene_bulk_mat = readh5_loom("./data/10X_5CL/bulk.loom")
gene_bulk_filt0 = round(gene_bulk_mat[!grepl('^MT-', rownames(gene_bulk_mat)), ])
gene_bulk_filt1 = gene_bulk_filt0[rowSums(gene_bulk_filt0 > 0) > 0, ]
bulk_sample_cell_type = sapply(colnames(gene_bulk_filt1), function(x){
  return(strsplit(x, "_", fixed = T)[[1]][[1]])
})
bulk_DEG_list = list()
celltype_combination = combn(unique(bulk_sample_cell_type), 2)
for(ii in seq(ncol(celltype_combination))){
  used_sample = bulk_sample_cell_type[bulk_sample_cell_type %in% celltype_combination[, ii]]
  this_name = paste(celltype_combination[, ii], collapse = "_")
  design_mat = cbind(1, ifelse(used_sample == used_sample[1], 1, 0))
  fit <- eBayes(lmFit(voom(gene_bulk_filt1[, names(used_sample)], design = design_mat), design = design_mat))
  bulk_DEG_list[[this_name]] = list()
  bulk_DEG_list[[this_name]][["DE_matrix"]] = topTable(fit, coef = 2, number = nrow(gene_bulk_filt1))
  bulk_DEG_list[[this_name]][["DEG"]] = rownames(bulk_DEG_list[[this_name]][["DE_matrix"]])[abs(bulk_DEG_list[[this_name]][["DE_matrix"]][, "logFC"]) >= 1.5 & bulk_DEG_list[[this_name]][["DE_matrix"]][, "adj.P.Val"] < 0.05]
}
```
### Identify DEGs using imputed results.
```{r}
if(!file.exists("./results/10X_5CL/sc_DEG_list.rds")){
  dir.create("./results/10X_5CL", showWarnings = F, recursive = T)
  sc_celltype = sapply(get_loom_cell("./data/10X_5CL/gene_selection.loom"), function(x){
    return(strsplit(x, "_", fixed = T)[[1]][[1]])
  })
  cell_type = factor(sc_celltype, levels = sort(unique(sc_celltype)))
  sc_gene = get_loom_gene("./data/10X_5CL/gene_selection.loom")
  sc_DEG_list = list()
  celltype_combination = combn(unique(sc_celltype), 2)
  DEG_method = c("MAST", "wilcox")
  run_task_matrix = matrix(nrow = ncol(celltype_combination) * length(DEG_method) * length(method_name), ncol = 4, dimnames = list(c(), c("method_name", "DEG_method", "celltype_1", "celltype_2")))
  run_task_matrix[, c(3, 4)] = rep(t(celltype_combination), each = length(DEG_method) * length(method_name))
  run_task_matrix[, 2] = rep(rep(DEG_method, each = length(method_name)), ncol(celltype_combination))
  run_task_matrix[, 1] = rep(method_name, length(DEG_method) * ncol(celltype_combination))
  for(ii in DEG_method){
    sc_DEG_list[[ii]] = list()
    for(jj in method_name){
      sc_DEG_list[[ii]][[jj]] = list()
    }
  }
  library(parallel)
  no_cores <- max(c(detectCores() - 1, 1))
  cl <- makeCluster(no_cores)
  clusterExport(cl, varlist = c("sc_gene", "cell_type", "run_task_matrix", "readh5_loom"))
  return_list = parLapply(cl, seq(nrow(run_task_matrix)), function(ii){
    library(Seurat)
    library(rhdf5)
    this_task = run_task_matrix[ii, ]
    celltype_1 = this_task["celltype_1"]
    celltype_2 = this_task["celltype_2"]
    this_celltype = cell_type[cell_type %in% c(celltype_1, celltype_2)]
    if(this_task["method_name"] == "Raw"){
      gene_bc_expression = readh5_loom("./data/10X_5CL/raw.loom")[sc_gene, names(this_celltype)]
    }else{
      gene_bc_expression = readh5_loom(paste0("./data/10X_5CL/", this_task["method_name"], ".loom"))[sc_gene, names(this_celltype)]
    }
    seurat_obj = CreateSeuratObject(counts = as.data.frame(gene_bc_expression), min.cells = 0, min.features = 0)
    seurat_obj = NormalizeData(seurat_obj, normalization.method = "LogNormalize", scale.factor = 10000)
    seurat_obj@active.ident = this_celltype
    suppressWarnings({DEG_result = FindMarkers(seurat_obj, ident.1 = celltype_1, ident.2 = celltype_2, min.pct = 0.1, logfc.threshold = 0, test.use = this_task["DEG_method"], verbose = F)})
    return(DEG_result)
  })
  stopCluster(cl)
  for(ii in seq(length(return_list))){
    this_task = run_task_matrix[ii, ]
    sc_DEG_list[[this_task["DEG_method"]]][[this_task["method_name"]]][[paste0(this_task["celltype_1"], "_", this_task["celltype_2"])]] = return_list[[ii]]
  }
  saveRDS(sc_DEG_list, paste0("./results/10X_5CL/sc_DEG_list.rds"))
}else{
  sc_DEG_list = readRDS(paste0("./results/10X_5CL/sc_DEG_list.rds"))
}
```
### False detected DEG test.
```{r}
if(!file.exists("./results/10X_5CL/sc_false_DEG_list.rds")){
  dir.create("./results/10X_5CL", showWarnings = F, recursive = T)
  sc_gene = get_loom_gene("./data/10X_5CL/gene_selection.loom")
  sc_celltype = sapply(get_loom_cell("./data/10X_5CL/gene_selection.loom"), function(x){
    return(strsplit(x, "_", fixed = T)[[1]][[1]])
  })
  cell_type = factor(sc_celltype, levels = sort(unique(sc_celltype)))
  cell_1 = names(cell_type[cell_type == "A549"])
  cell_number_combination = as.matrix(expand.grid(c(10, 50, 100, 500), c(10, 50, 100, 500)))
  cell_number_combination = cell_number_combination[cell_number_combination[, 1] <= cell_number_combination[, 2], ]
  DEG_method = c("MAST", "wilcox")
  run_task_matrix = matrix(nrow = nrow(cell_number_combination) * length(DEG_method) * length(method_name), ncol = 4, dimnames = list(c(), c("method_name", "DEG_method", "cell_number_1", "cell_number_2")))
  run_task_matrix[, c(3, 4)] = rep(cell_number_combination, each = length(DEG_method) * length(method_name))
  run_task_matrix[, 2] = rep(rep(DEG_method, each = length(method_name)), ncol(cell_number_combination))
  run_task_matrix[, 1] = rep(method_name, length(DEG_method) * ncol(cell_number_combination))
  sc_false_DEG_list = list()
  for(ii in DEG_method){
    sc_false_DEG_list[[ii]] = list()
    for(jj in method_name){
      sc_false_DEG_list[[ii]][[jj]] = list()
    }
  }
  library(parallel)
  no_cores <- max(c(detectCores() - 1, 1))
  cl <- makeCluster(no_cores)
  clusterExport(cl, varlist = c("sc_gene", "cell_1", "run_task_matrix", "readh5_loom"))
  return_list = parLapply(cl, seq(nrow(run_task_matrix)), function(ii){
    library(Seurat)
    library(rhdf5)
    this_task = run_task_matrix[ii, ]
    cell_number_1 = as.numeric(this_task["cell_number_1"])
    cell_number_2 = as.numeric(this_task["cell_number_2"])
    set.seed(12345)
    sampled_cells = cell_1[sample(seq(length(cell_1)), cell_number_1 + cell_number_2)]
    this_celltype = c(rep("cn1", cell_number_1), rep("cn2", cell_number_2))
    names(this_celltype) = sampled_cells
    this_celltype = factor(this_celltype, levels = c("cn1", "cn2"))
    if(this_task["method_name"] == "Raw"){
      gene_bc_expression = readh5_loom("./data/10X_5CL/raw.loom")[sc_gene, names(this_celltype)]
    }else{
      gene_bc_expression = readh5_loom(paste0("./data/10X_5CL/", this_task["method_name"], ".loom"))[sc_gene, names(this_celltype)]
    }
    seurat_obj = CreateSeuratObject(counts = as.data.frame(gene_bc_expression), min.cells = 0, min.features = 0)
    seurat_obj = NormalizeData(seurat_obj, normalization.method = "LogNormalize", scale.factor = 10000)
    seurat_obj@active.ident = this_celltype
    suppressWarnings({DEG_result = FindMarkers(seurat_obj, ident.1 = "cn1", ident.2 = "cn2", min.pct = 0.1, logfc.threshold = 0, test.use = this_task["DEG_method"], verbose = F)})
    return(DEG_result)
  })
  stopCluster(cl)
  for(ii in seq(length(return_list))){
    this_task = run_task_matrix[ii, ]
    sc_false_DEG_list[[this_task["DEG_method"]]][[this_task["method_name"]]][[paste0(this_task["cell_number_1"], "_", this_task["cell_number_2"])]] = return_list[[ii]]
  }
  saveRDS(sc_false_DEG_list, paste0("./results/10X_5CL/sc_false_DEG_list.rds"))
}else{
  sc_false_DEG_list = readRDS(paste0("./results/10X_5CL/sc_false_DEG_list.rds"))
}
```
Note: This result has tiny difference from our paper as the annotation version is different. 
```{r}
overlap_MAST = sapply(sc_DEG_list[["MAST"]], function(x){
  return(sapply(names(x), function(y){
    test_df = x[[y]][order(x[[y]][, "p_val_adj"]), ]
    test_result = rownames(test_df) %in% bulk_DEG_list[[y]][["DEG"]]
    return(mean(sapply(seq(100) * 10, function(z){
      return(mean(test_result[seq(z)]))
    })))
  }))
})
overlap_wilcox = sapply(sc_DEG_list[["wilcox"]], function(x){
  return(sapply(names(x), function(y){
    test_df = x[[y]][order(x[[y]][, "p_val_adj"]), ]
    test_result = rownames(test_df) %in% bulk_DEG_list[[y]][["DEG"]]
    return(mean(sapply(seq(100) * 10, function(z){
      return(mean(test_result[seq(z)]))
    })))
  }))
})
print(colMeans(overlap_MAST))
print(colMeans(overlap_wilcox))
```
```{r}
#  Note: This result has tiny difference from our paper as the sample cell is different.
DEG_MAST_false = sapply(sc_false_DEG_list[["MAST"]], function(x){
  return(sapply(x, function(y){
    return(sum(y[, "p_val"] <= 0.01 & abs(y[, "avg_logFC"]) >= 0.25))
  }))
})
MAST_false_mean = colMeans(DEG_MAST_false)
print(MAST_false_mean)
DEG_wilcox_false = sapply(sc_false_DEG_list[["wilcox"]], function(x){
  return(sapply(x, function(y){
    return(sum(y[, "p_val"] <= 0.01 & abs(y[, "avg_logFC"]) >= 0.25))
  }))
})
wilcox_false_mean = colMeans(DEG_wilcox_false)
print(wilcox_false_mean)
```

```{r fig.height=3, fig.width=3}
library(ggrepel)
plot_df = data.frame(omo = (1 - colMeans(overlap_MAST)[method_name]), fm = MAST_false_mean[method_name], method = method_name)
ggplot(plot_df, aes(x = fm, y = omo, label = method, color = method)) + geom_point() + geom_text_repel() + theme_bw() + theme(legend.position = "none") + xlab("False DEG (293T)") + ylab("1 - Overlap") + ggtitle("MAST") + scale_colour_manual(values = method_color)
plot_df = data.frame(omo = (1 - colMeans(overlap_wilcox)[method_name]), fm = wilcox_false_mean[method_name], method = method_name)
ggplot(plot_df, aes(x = fm, y = omo, label = method, color = method)) + geom_point() + geom_text_repel() + theme_bw() + theme(legend.position = "none") + xlab("False DEG (293T)") + ylab("1 - Overlap") + ggtitle("wilcox") + scale_colour_manual(values = method_color)
```








