---
title: "Data preparation for 10X_5CL"
output: html_notebook
---
### Setup knitr and load utility functions
```{r setup}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir="E:/DISC/reproducibility")
```
```{r}
utilities_path = "./source/utilities.r"
source(utilities_path)
```
### Generate data file
The original 10X_5CL data can be found at https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE126906.</br>
The filtered 10X_5CL data can be found at https://github.com/LuyiTian/sc_mixology/blob/master/data/csv/sc_10x_5cl.count.csv.gz.</br>
We use 3918 filtered cells and all genes to make raw.loom (genes will be filtered in the following step gene selection as our DISC paper).
```{r}
if(!file.exists("./data/10X_5CL/raw.loom")){
  original_data = as.matrix(read.csv("./data/10X_5CL/original_data/GSM3618014_gene_count.csv.gz", header = T, sep = ",", row.names = 1))# 32895  5001
  geneid_genename = readRDS("./data/hg19/geneid_genename.rds")
  gene_name_candidate = geneid_genename[rownames(original_data)]
  gene_name = rownames(original_data)
  gene_name[!is.na(gene_name_candidate)] = gene_name_candidate[!is.na(gene_name_candidate)]
  for(ii in gene_name[duplicated(gene_name)]){
    index = 0
    for(jj in which(gene_name == ii)){
      gene_name[jj] = paste0(gene_name[jj], "_duplicate_", index)
      index = index + 1
    }
  }
  rownames(original_data) = gene_name
  print(dim(original_data))
  save_h5("./data/10X_5CL/original.loom", t(original_data))
  filtered_data = read.csv("./data/10X_5CL/original_data/sc_10x_5cl.count.csv.gz", header = T, row.names = 1)
  cell_id = colnames(filtered_data)
  raw_data = as.matrix(original_data[, cell_id])
  print(dim(raw_data))
  save_h5("./data/10X_5CL/raw.loom", t(raw_data))
}else{
  raw_data = readh5_loom("./data/10X_5CL/raw.loom")
  cell_id = colnames(raw_data)
  gene_name = rownames(raw_data)
  print(dim(raw_data))
}
print("10X_5CL...OK!")
```
The bulk data can be found at https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE86337. </br>
```{r}
if(!file.exists("./data/10X_5CL/bulk.loom")){
  library(org.Hs.eg.db)
  gene_bulk_mat_raw = as.matrix(read.table("./data/10X_5CL/original_data/GSE86337_reverse.stranded.unfiltered.count.matrix.txt.gz", header = T, row.names = 1, sep = "\t"))
  sample_mapping = as.matrix(read.csv("./data/10X_5CL/original_data/GSE86337_sample_id_sample_name.txt", sep = "\t"))
  sample_name = sample_mapping[, 2]
  names(sample_name) = sample_mapping[, 1]
  colnames(gene_bulk_mat_raw) = sample_name[colnames(gene_bulk_mat_raw)]
  gene_name_all = select(org.Hs.eg.db, key = as.character(rownames(gene_bulk_mat_raw)), columns = c("SYMBOL"), keytype = "ENTREZID")$SYMBOL
  rownames(gene_bulk_mat_raw) = gene_name_all
  gene_bulk_filt_0 = gene_bulk_mat_raw[!is.na(gene_name_all), ]
  gene_name_used = rownames(gene_bulk_filt_0)
  used_index = sapply(unique(gene_name_used), function(x){
    this_index = which(gene_name_used == x)
    if(length(this_index) > 1){
      return(this_index[which.max(rowSums(gene_bulk_filt_0[this_index, ]))])
    }else{
      return(this_index)
    }
  })
  gene_bulk_mat = gene_bulk_filt_0[used_index, ]
  save_h5("./data/10X_5CL/bulk.loom", as.matrix(t(gene_bulk_mat)))
}else{
  gene_bulk_mat = readh5_loom("./data/10X_5CL/bulk.loom")
}
print(dim(gene_bulk_mat))
print("10X_5CL_Bulk...OK!")
```
